### ISSUE TITLE
Traceback after time of use

### ISSUE THREAD

**Issue by Inbaos** [Pymmdrza/Dumper-Mnemonic#3]
Hey,
i use this script since yesterday today i see an traceback error in line 162 bnb_bal = CheckBalanceBNB(bnb_addr)
and in another one a traceback error in line 163 doge_bal = CheckBalanceDogecoin(doge_addr)

is there any error in the script?

thx

**Comment by Inbaos** [comment]
this is the error complete
Traceback (most recent call last):
  File "/home/dum/DumperMnemonic.py", line 163, in <module>
    doge_bal = CheckBalanceDogecoin(doge_addr)
  File "/home/dum/DumperMnemonic.py", line 107, in CheckBalanceDogecoin
    req = requests.get(url)
  File "/usr/local/lib/python3.10/dist-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 547, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
``

**Comment by Pymmdrza** [comment]
> this is the error complete Traceback (most recent call last): File "/home/dum/DumperMnemonic.py", line 163, in doge_bal = CheckBalanceDogecoin(doge_addr) File "/home/dum/DumperMnemonic.py", line 107, in CheckBalanceDogecoin req = requests.get(url) File "/usr/local/lib/python3.10/dist-packages/requests/api.py", line 73, in get return request("get", url, params=params, **kwargs) File "/usr/local/lib/python3.10/dist-packages/requests/api.py", line 59, in request return session.request(method=method, url=url, **kwargs) File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 587, in request resp = self.send(prep, **send_kwargs) File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 701, in send r = adapter.send(request, **kwargs) File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 547, in send raise ConnectionError(err, request=request) requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')) ``

It is available without any problem and no interference is observed. Please refrain from manipulating and editing the script. Proceed as shown in the Screen

[![asciicast](https://asciinema.org/a/646448.svg)](https://asciinema.org/a/646448)

**Comment by WilliamsRegae** [comment]
Works perfectly.. but for days now can't find and wallets with balance
